### ISSUE TITLE
Detailed documentations and example

### ISSUE THREAD

**Issue by sujit77** [kiln/flourish-slider#1]
Hi,

I was searching for similar libraries to develop `circular slider` and found this one.
The description says that it can support all kinds of sliders (linear and circular).

Can you improve documentatios little bit more and include examples to contain circular slider along with label marker(which I think is possible in this one)?

Thank you

**Comment by theduncanclark** [comment]
I'm afraid this library doesn't support circular sliders. just circular slider handles. We may add it in the future but we have no plans for this at the present.
